server {
	# Слушаем порты 80 443
	# listen 80;
	# listen [::]:80;
	# listen 443 ssl;
	# listen [::]:443 ssl;
	listen 3000;

	# Задаем корневой каталог для запрос к серверу
	root /var/www/roundmap.app;
	index index.html;

	# Указываем какие имена серверов будут обрабатываться в этом блоке server
	server_name *.roundmap.app 185.146.157.206;

	# Настроки на SSL
	ssl_certificate /etc/ssl/roundmap/roundmap.crt;
    ssl_certificate_key /etc/ssl/roundmap/roundmap.key;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers HIGH:!aNULL:!MD5;

	# Пути для логов
	access_log /var/log/nginx/nginx.vhost.access.log;
	error_log /var/log/nginx/nginx.vhost.error.log;

	# Редирект на https
	if ($scheme = http) {
        return 301 https://$server_name$request_uri;
    }
}
